Added autoDelegations management
icure-io/icure-medical-device-js-sdk pull request #18
Opened 2022-09-07 13:58 UTC by LotuxPunk

2022-09-09 09:32 UTC, LotuxPunk commented on package.json
> +    "test-user": "nyc mocha test/apis/user-api.ts --require ts-node/register --require source-map-support/register --timeout=60000 --recursive"
```suggestion

```

2022-09-12 08:54 UTC, lisatr2812 requested changes

2022-09-12 08:54 UTC, lisatr2812 commented on src/apis/UserApi.ts
> +  addAutoDelegationsTo(type: DelegationTag, user: User, to: string[]): Promise<User>
Rename it to `shareAllFutureDataWith(sharedDataType: SharedDataType, dataOwnerIds: string[])`

2022-09-12 08:54 UTC, lisatr2812 commented on src/apis/UserApi.ts
> +  addAutoDelegationsTo(type: DelegationTag, user: User, to: string[]): Promise<User>
`user` does not need to be used in this method : The service can be called only for the current user. 
Meaning user may only be the usserApi.getCurrentUser(), which you can call directly in the service

2022-09-12 08:54 UTC, lisatr2812 commented on src/apis/UserApi.ts
> +  removeAutoDelegationsTo(type: DelegationTag, user: User, to: string[]): Promise<User>
`user` does not need to be used in this method : The service can be called only for the current user. 
Meaning user may only be the usserApi.getCurrentUser(), which you can call directly in the service

2022-09-12 08:54 UTC, lisatr2812 commented on src/apis/UserApi.ts
> +  removeAutoDelegationsTo(type: DelegationTag, user: User, to: string[]): Promise<User>
Rename it to `stopSharingDataWith(sharedDataType: SharedDataType, dataOwnerIds: string[])`

2022-09-12 08:54 UTC, lisatr2812 commented on src/apis/impl/UserApiImpl.ts
> +    if (user.autoDelegations[type]) {
`const user = this.userApi.getCurrentUser()`

2022-09-12 08:54 UTC, lisatr2812 commented on src/apis/impl/UserApiImpl.ts
> +      newAutoDelegations = Object.entries(user.autoDelegations).reduce((accumulator, [key, values]) => {
Rename `newAutoDelegations` to `newDataSharing`

2022-09-12 08:54 UTC, lisatr2812 commented on src/apis/impl/UserApiImpl.ts
> +        autoDelegations: newAutoDelegations as { [key in DelegationTag]: Set<string> }
Rename user property `autoDelegations` to `sharingDataWith`

2022-09-12 08:54 UTC, lisatr2812 commented on src/apis/impl/UserApiImpl.ts
> +    const newAutoDelegations = Object.entries(user.autoDelegations).reduce((accumulator, [key, values]) => {
Rename `newAutoDelegations` to `newDataSharing`

2022-09-12 08:54 UTC, lisatr2812 commented on src/mappers/user.ts
> +        autoDelegations: toMapSet(obj.autoDelegations) as { [key in DelegationTag]: Set<string>; } | undefined,
Rename user property (only in MedTech !) `autoDelegations` to `sharingDataWith`

2022-09-12 08:54 UTC, lisatr2812 commented on src/models/User.ts
> +  'autoDelegations': { [key in DelegationTag]: Set<string>; };
Rename user property (only in MedTech !) `autoDelegations` to `sharingDataWith`

2022-09-12 08:54 UTC, lisatr2812 commented on src/models/User.ts
> +   * Delegations that are automatically generated client side when a new database object is created by this user
`Ids of the dataOwners with who the user is sharing all new data he is creating in iCure : All Data Types that may be shared can be found in SharedDataType enum`

2022-09-12 08:54 UTC, lisatr2812 commented on src/models/User.ts
> +  'autoDelegations': { [key in DelegationTag]: Set<string>; };
Rename `DelegationTag` to `SharedDataType`

2022-09-12 08:54 UTC, lisatr2812 commented on src/models/User.ts
> +export type DelegationTag =
Rename `DelegationTag` to `SharedDataType`

2022-09-12 08:54 UTC, lisatr2812 commented on src/models/User.ts
> +export type DelegationTag =
In this enum, let's only use the following ones : 
```
all,
administrativeData,
generalInformation,
financialInformation,
medicalInformation,
sensitiveInformation,
confidentialInformation
```
The other values are very specific to Belgium codes, let's try to not expose it first. We can expose it later if needed

2022-09-12 08:54 UTC, lisatr2812 commented on test/apis/hcp-user.ts
> +const tmp = os.tmpdir();
Use the `setLocalStorage(fetch)` method available in test-utils

2022-09-12 08:54 UTC, lisatr2812 commented on test/apis/user-api.ts
> +(global as any).localStorage = new (require('node-localstorage').LocalStorage)(tmpdir(), 5 * 1024 * 1024 * 1024)
Use the setLocalStorage(fetch) method available in test-utils

2022-09-12 08:54 UTC, lisatr2812 commented on test/apis/user-api.ts
> +  it('Management of auto-delegations', async () => {
Rename your test to `a user is able to share data with another dataOwner, and stop sharing data with him later`

Add the following test as well : 
- `When a user already shares data with the provided dataOwner, the user is returned successfully, without any additional request to iCure` and check that the user is exactly the same than the provided one

2022-09-12 14:58 UTC, merged